encoding: utf-8
baseurl: /ruby101
url: www.falexandrou.com/ruby101/
permalink: /:title/
ga_tracking_code: UA-70676378-3
disqus_shortname: ruby101
prose:
  media: /img
  ignore:
    - /_includes
    - /_layouts
    - /_sass
    - /fonts
    - /js
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "course_page"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "category"
        field:
          element: "hidden"
          value: "content"
